### ISSUE TITLE
use of uninitialized variables

### ISSUE THREAD

**Issue by jornbr** [inogs/bfmforfabm#1]
In `bfm_pelagic_base.F90`, two variables, `c0` and `s0`, are being used without having been set:

https://github.com/inogs/bfmforfabm/blob/8c5483c0306badc1a303187ffd7c26c7ac154ced/bfm_pelagic_base.F90#L81
https://github.com/inogs/bfmforfabm/blob/8c5483c0306badc1a303187ffd7c26c7ac154ced/bfm_pelagic_base.F90#L96

This was picked up by ifort after compiling with additional debugging flags (`/check:all /Qtrapuv /Qinit:snan,arrays` on Windows). Likely the desired behaviour is to have a background value of 0, which would mean that `c0` and `s0` can be replaced by `0.0_rk`.

**Comment by plazzari** [comment]
Thank you Jorn.
 I think what you propose makes sense we will give a look and fix it.

Best,
 Paolo

Il giorno mar 28 nov 2023 alle ore 17:31 Jorn Bruggeman <
***@***.***> ha scritto:

**Comment by plazzari** [comment]
We tested the suggested bug fix and pushed on dev_monospectral.
To close the issue we will push the correction on the other branches.

**Comment by ealvarez-s** [comment]
Pushed to dev_1D as well.
