### ISSUE TITLE
compiler warning

### ISSUE THREAD

**Issue by jornbr** [inogs/bfmforfabm#2]
When compiling with gfortran,

https://github.com/inogs/bfmforfabm/blob/27d4cd69c53ac0372b464482a9ac7393bf83af5a/PelBac.F90#L710

currently triggers

```
PelBac.F90:710:61:

  710 |  _SET_DIAGNOSTIC_(self%id_B_P_O3h,-(rep1) + -rep)
      |                                                             1
Warning: Extension: Unary operator following arithmetic operator (use parentheses) at (1)
```

This is in the `dev_monospectral` branch, but the same line appears to be present in the `master` branch too.

This just for info, as compilation still completes successfully.

**Comment by plazzari** [comment]
Following your comment, the monospectral branch has been corrected, correction needs to be applied to other branches.

**Comment by ealvarez-s** [comment]
Corrected in dev_1D.
