### ISSUE TITLE
Wrong sink for phyto phosphorous excretion?

### ISSUE THREAD

**Issue by ealvarez-s** [inogs/bfmforfabm#5]
https://github.com/inogs/bfmforfabm/blob/ecad9e98c2e14fb4326b3e8916e1b4c6ea2f9243/Phyto.F90#L918
This line should excrete P to DOP (R1p) and not POP (R6p)?
  _SET_ODE_(self%id_R1p,rr1p)

**Comment by plazzari** [comment]
Bug fix [committed](https://github.com/inogs/bfmforfabm/commit/876586968637f80b611f6276aef0cc5149cf99df)

**Comment by plazzari** [comment]
closed issue. Tested simulation at BOUSSOLE.
